default: &default

  photo_style_thumb:
    - '100x100#'
    - :jpg

  photo_style_original:
    -

  photo_style_showed:
    - '800x800>'
    - :jpg

  photo_convert_options:
    {
      thumb: '-quality 80 -strip',
      original: '',
      showed: '-quality 100 -strip'
      }

  photo_content_types:
    - 'image/jpeg'
    - 'image/gif'
    - 'image/png'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
